services:
    db:
      image: mysql
      restart: always
      ports: 
        - 3306:3306
      env_file:
        - backend-variables.env      
      volumes:
        - "./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql"
    web-node:
        build: "./node"
        ports:
          - 8080:3000
        env_file:
          - backend-variables.env
        volumes:
          - image-storage:/usr/src/app-node/storage
        depends_on:
          - db
    #web-python:
     #   env_file:
      #    - backend-variables.env
       # build: "./python"
        #volumes:
         # - image-storage:/usr/src/app-python/storage
        #ports:
         # - 8081:8080

volumes:
  image-storage: